// src/services/mockData.ts

import { SAe } from '../types/sae.types';

export const MOCK_SAES: SAe[] = [
  {
    id: 1,
    titre: 'Portfolio interactif React',
    description: "Conception et développement d'un portfolio responsive en React avec animations avancées et CMS headless.",
    annee: 'MMI3',
    semestre: 5,
    domaine: 'Développement',
    competences: ['Concevoir', 'Développer'],
    ue: 'UE5.1',
    images: [
      'https://picsum.photos/seed/sae1a/800/500',
      'https://picsum.photos/seed/sae1b/800/500',
      'https://picsum.photos/seed/sae1c/800/500',
    ],
    auteurs: ['Alice Martin', 'Bob Dupont'],
    dateDebut: '2025-09-01',
    dateFin: '2025-11-30',
    note: 17.5,
    tauxReussite: 92,
    lienSite: 'https://portfolio-mmi.vercel.app',
    lienProduction: 'https://github.com/mmi3/portfolio',
  },
  {
    id: 2,
    titre: 'Application 3D de visite virtuelle',
    description: 'Visite virtuelle interactive avec Three.js, navigation immersive dans un musée.',
    annee: 'MMI3',
    semestre: 6,
    domaine: '3D',
    competences: ['Concevoir', 'Exprimer', 'Développer'],
    ue: 'UE6.2',
    images: [
      'https://picsum.photos/seed/sae2a/800/500',
      'https://picsum.photos/seed/sae2b/800/500',
    ],
    auteurs: ['Clara Petit', 'David Moreau', 'Emma Bernard'],
    dateDebut: '2026-01-10',
    dateFin: '2026-03-15',
    note: 19,
    tauxReussite: 98,
    lienSite: 'https://musee-virtuel.netlify.app',
    lienProduction: 'https://github.com/mmi3/musee-3d',
  },
  {
    id: 3,
    titre: 'Campagne de communication digitale',
    description: "Création d'une campagne complète pour une association locale : identité visuelle, réseaux sociaux, site web.",
    annee: 'MMI2',
    semestre: 4,
    domaine: 'Communication',
    competences: ['Comprendre', 'Concevoir', 'Exprimer'],
    ue: 'UE4.3',
    images: [
      'https://picsum.photos/seed/sae3a/800/500',
      'https://picsum.photos/seed/sae3b/800/500',
      'https://picsum.photos/seed/sae3c/800/500',
    ],
    auteurs: ['Félix Renard', 'Gabrielle Simon'],
    dateDebut: '2025-02-01',
    dateFin: '2025-04-30',
    note: 15,
    tauxReussite: 78,
    lienSite: 'https://asso-comm.fr',
    lienProduction: 'https://figma.com/mmi2/campagne',
  },
  {
    id: 4,
    titre: 'Interface de gestion d\'inventaire',
    description: 'Application web full-stack (Spring Boot + Vue.js) pour la gestion d\'un stock de matériel audiovisuel.',
    annee: 'MMI2',
    semestre: 3,
    domaine: 'Développement',
    competences: ['Développer', 'Entreprendre'],
    ue: 'UE3.1',
    images: [
      'https://picsum.photos/seed/sae4a/800/500',
      'https://picsum.photos/seed/sae4b/800/500',
    ],
    auteurs: ['Hugo Lambert', 'Inès Rousseau'],
    dateDebut: '2024-09-15',
    dateFin: '2024-12-20',
    note: 14,
    tauxReussite: 70,
    lienSite: 'https://inventaire-mmi.fr',
    lienProduction: 'https://github.com/mmi2/inventaire',
  },
  {
    id: 5,
    titre: 'Expérience de design interactif',
    description: 'Installation interactive pilotée par capteurs de mouvement, aux frontières de l\'art digital et de l\'UX.',
    annee: 'MMI3',
    semestre: 5,
    domaine: 'Création',
    competences: ['Exprimer', 'Concevoir'],
    ue: 'UE5.2',
    images: [
      'https://picsum.photos/seed/sae5a/800/500',
      'https://picsum.photos/seed/sae5b/800/500',
      'https://picsum.photos/seed/sae5c/800/500',
    ],
    auteurs: ['Jules Fontaine', 'Karine Lefebvre', 'Louis Garnier'],
    dateDebut: '2025-10-01',
    dateFin: '2025-12-10',
    note: 18,
    tauxReussite: 90,
    lienSite: 'https://art-interact.vercel.app',
    lienProduction: 'https://github.com/mmi3/art-interactif',
  },
];
